# Generated by Django 6.0.6 on 2026-07-28 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_profile_image'),
        ('cart', '0003_coupon_alter_cartitem_cart_cart_coupon'),
        ('products', '0006_product_stock_alter_product_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='products.product'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='size_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items', to='products.sizevariant'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_price',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='minimum_amount',
            field=models.PositiveIntegerField(default=500),
        ),
    ]
