# Generated by Django 6.0.6 on 2026-07-23 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_coupon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
